# Level 2: Data Processing & Feature Engineering

## Project Objective

The objective of Level 2 is to process the train schedule data and create useful features for further analysis. This includes standardizing schedule time fields, calculating journey duration, classifying routes based on distance, and generating station-wise train frequency.

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../DATASET/Dataset1.csv")

In [4]:
df.head()

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0

In [5]:
df[["Train_No", "Station_Name", "Arrival_time", "Departure_Time"]].head(10)

   Train_No  Station_Name Arrival_time Departure_Time
0       107  SAWANTWADI R     00:00:00       10:25:00
1       107        THIVIM     11:06:00       11:08:00
2       107       KARMALI     11:28:00       11:30:00
3       107   MADGOAN JN.     12:10:00       00:00:00
4       108   MADGOAN JN.     00:00:00       20:30:00
5       108       KARMALI     21:04:00       21:06:00
6       108        THIVIM     21:26:00       21:28:00
7       108  SAWANTWADI R     22:25:00       00:00:00
8       128   MADGOAN JN.     19:40:00       19:40:00
9       128       KARMALI     20:18:00       20:20:00

In [6]:
df[["Arrival_time", "Departure_Time"]].dtypes

Arrival_time      str
Departure_Time    str
dtype: object

## Standardize Schedule Time Fields

Arrival and departure time fields are converted into a consistent datetime/time representation to support journey duration calculations and further time-based analysis.

In [8]:
print(df["Arrival_time"].head(10))
print(df["Departure_Time"].head(10))

0    00:00:00
1    11:06:00
2    11:28:00
3    12:10:00
4    00:00:00
5    21:04:00
6    21:26:00
7    22:25:00
8    19:40:00
9    20:18:00
Name: Arrival_time, dtype: str
0    10:25:00
1    11:08:00
2    11:30:00
3    00:00:00
4    20:30:00
5    21:06:00
6    21:28:00
7    00:00:00
8    19:40:00
9    20:20:00
Name: Departure_Time, dtype: str

In [9]:
print(df["Arrival_time"].dtype)
print(df["Departure_Time"].dtype)

str
str

In [10]:
df["Arrival_time"] = pd.to_datetime(df["Arrival_time"], format="%H:%M:%S")
df["Departure_Time"] = pd.to_datetime(df["Departure_Time"], format="%H:%M:%S")

In [11]:
df[["Arrival_time", "Departure_Time"]].dtypes

Arrival_time      datetime64[us]
Departure_Time    datetime64[us]
dtype: object

In [12]:
df.groupby("Train_No").agg(
    Start_Time=("Departure_Time", "first"),
    End_Time=("Arrival_time", "last")
).head(10)

                  Start_Time            End_Time
Train_No
107      1900-01-01 10:25:00 1900-01-01 12:10:00
108      1900-01-01 20:30:00 1900-01-01 22:25:00
128      1900-01-01 19:40:00 1900-01-01 17:45:00
290      1900-01-01 18:30:00 1900-01-01 02:30:00
401      1900-01-01 21:30:00 1900-01-01 10:00:00
421      1900-01-01 23:00:00 1900-01-01 08:00:00
422      1900-01-01 11:45:00 1900-01-01 14:30:00
477      1900-01-01 12:10:00 1900-01-01 15:20:00
502      1900-01-01 10:30:00 1900-01-01 09:30:00
504      1900-01-01 09:00:00 1900-01-01 10:00:00

In [13]:
df[["Train_No", "SN", "Station_Name", "Arrival_time", "Departure_Time"]].head(20)

    Train_No  SN  Station_Name        Arrival_time      Departure_Time
0        107   1  SAWANTWADI R 1900-01-01 00:00:00 1900-01-01 10:25:00
1        107   2        THIVIM 1900-01-01 11:06:00 1900-01-01 11:08:00
2        107   3       KARMALI 1900-01-01 11:28:00 1900-01-01 11:30:00
3        107   4   MADGOAN JN. 1900-01-01 12:10:00 1900-01-01 00:00:00
4        108   1   MADGOAN JN. 1900-01-01 00:00:00 1900-01-01 20:30:00
5        108   2       KARMALI 1900-01-01 21:04:00 1900-01-01 21:06:00
6        108   3        THIVIM 1900-01-01 21:26:00 1900-01-01 21:28:00
7        108   4  SAWANTWADI R 1900-01-01 22:25:00 1900-01-01 00:00:00
8        128   1   MADGOAN JN. 1900-01-01 19:40:00 1900-01-01 19:40:00
9        128   2       KARMALI 1900-01-01 20:18:00 1900-01-01 20:20:00
10       128   3        THIVIM 1900-01-01 20:40:00 1900-01-01 20:42:00
11       128   4  SAWANTWADI R 1900-01-01 21:16:00 1900-01-01 21:18:00
12       128   5         KUDAL 1900-01-01 21:38:00 1900-01-01 21:40:00
13       128   6   SINDHU DURG 1900-01-01 21:54:00 1900-01-01 21:56:00
14       128   7     KANKAVALI 1900-01-01 22:18:00 1900-01-01 22:20:00
15       128   8   VAIBHAVWADI 1900-01-01 22:40:00 1900-01-01 22:42:00
16       128   9  RAJAPUR ROAD 1900-01-01 22:56:00 1900-01-01 22:58:00
17       128  10     RATNAGIRI 1900-01-01 23:52:00 1900-01-01 23:57:00
18       128  11   SANGMESHWAR 1900-01-01 00:34:00 1900-01-01 00:36:00
19       128  12       CHIPLUN 1900-01-01 01:10:00 1900-01-01 01:12:00

In [14]:
df[df["Train_No"] == 107][
    ["Train_No", "SN", "Station_Name", "Arrival_time", "Departure_Time"]
]

   Train_No  SN  Station_Name        Arrival_time      Departure_Time
0       107   1  SAWANTWADI R 1900-01-01 00:00:00 1900-01-01 10:25:00
1       107   2        THIVIM 1900-01-01 11:06:00 1900-01-01 11:08:00
2       107   3       KARMALI 1900-01-01 11:28:00 1900-01-01 11:30:00
3       107   4   MADGOAN JN. 1900-01-01 12:10:00 1900-01-01 00:00:00

In [15]:
print("Arrival 00:00:", (df["Arrival_time"].dt.time == pd.Timestamp("00:00:00").time()).sum())
print("Departure 00:00:", (df["Departure_Time"].dt.time == pd.Timestamp("00:00:00").time()).sum())

Arrival 00:00: 2003
Departure 00:00: 1970

In [16]:
df[(df["Arrival_time"].dt.time == pd.Timestamp("00:00:00").time()) |
   (df["Departure_Time"].dt.time == pd.Timestamp("00:00:00").time())][
    ["Train_No", "SN", "Station_Name", "Arrival_time", "Departure_Time"]
].head(20)

      Train_No  SN  Station_Name        Arrival_time      Departure_Time
0          107   1  SAWANTWADI R 1900-01-01 00:00:00 1900-01-01 10:25:00
3          107   4   MADGOAN JN. 1900-01-01 12:10:00 1900-01-01 00:00:00
4          108   1   MADGOAN JN. 1900-01-01 00:00:00 1900-01-01 20:30:00
7          108   4  SAWANTWADI R 1900-01-01 22:25:00 1900-01-01 00:00:00
990       4831   1   JODHPUR JN. 1900-01-01 00:00:00 1900-01-01 13:30:00
1011      4831  22   HARIDWAR JN 1900-01-01 10:45:00 1900-01-01 00:00:00
1328      5715   1  NEW JALPAIGU 1900-01-01 00:00:00 1900-01-01 03:00:00
1329      5715   2    KISHANGANJ 1900-01-01 05:10:00 1900-01-01 00:00:00
1330      5716   1    KISHANGANJ 1900-01-01 00:00:00 1900-01-01 04:00:00
1331      5716   2  NEW JALPAIGU 1900-01-01 06:30:00 1900-01-01 00:00:00
1332      5719   1   KATIHAR JN. 1900-01-01 00:00:00 1900-01-01 23:15:00
1342      5719  11  SILIGURI JN. 1900-01-01 03:15:00 1900-01-01 00:00:00
1343      5720   1  SILIGURI JN. 1900-01-01 00:00:00 1900-01-01 18:00:00
1353      5720  11   KATIHAR JN. 1900-01-01 23:00:00 1900-01-01 00:00:00
1870      6081   1    COIMBATORE 1900-01-01 00:00:00 1900-01-01 13:35:00
1873      6081   4      POLLACHI 1900-01-01 14:45:00 1900-01-01 00:00:00
1874      6082   1      POLLACHI 1900-01-01 00:00:00 1900-01-01 15:05:00
1877      6082   4    COIMBATORE 1900-01-01 16:15:00 1900-01-01 00:00:00
1878      6412   1  DELHI-SAFDAR 1900-01-01 00:00:00 1900-01-01 11:10:00
1898      6412  21      PAYYANUR 1900-01-01 16:20:00 1900-01-01 00:00:00